"""
CloudFail-Killer - Nuclei Template Exporter

Export discovered IPs to Nuclei YAML template format for
automated vulnerability scanning.

Nuclei is a fast vulnerability scanner by ProjectDiscovery.
Templates follow the Nuclei template specification.
"""

from __future__ import annotations

from pathlib import Path

from cloudkill import __version__
from cloudkill.core.models import ScanReport
from cloudkill.core.validator import safe_output_path


def export_nuclei_template(
    report: ScanReport,
    output_path: Path | str,
    author: str = "CloudKill",
    severity: str = "info",
) -> Path:
    """
    Export scan results as Nuclei HTTP template.

    Creates a Nuclei template that probes discovered origin IPs
    to verify they serve the target domain content.

    Args:
        report: ScanReport to export
        output_path: Output file path (directory or .yaml file)
        author: Template author attribution
        severity: Default severity level

    Returns:
        Path to the created template file
    """
    output_path = safe_output_path(output_path)

    # If directory, create filename from domain
    if output_path.is_dir() or not output_path.suffix:
        output_path = output_path / f"cloudkill-{report.domain.replace('.', '-')}.yaml"
    else:
        output_path.parent.mkdir(parents=True, exist_ok=True)

    if not output_path.suffix:
        output_path = output_path.with_suffix(".yaml")

    # Collect high-confidence IPs
    high_conf = [
        r for r in report.results
        if r.confidence >= 50 and not r.is_cloudflare
    ]
    high_conf.sort(key=lambda r: -r.confidence)

    # Build Nuclei template
    template_lines: list[str] = []

    # Template ID and info
    template_lines.append(f"id: cloudkill-origin-{report.domain.replace('.', '-')}")
    template_lines.append("")
    template_lines.append("info:")
    template_lines.append(f"  name: CloudFail-Killer Origin IP - {report.domain}")
    template_lines.append(f"  author: {author}")
    template_lines.append(f"  severity: {severity}")
    template_lines.append("  description: |")
    template_lines.append(f"    Origin IP addresses discovered behind Cloudflare for {report.domain}.")
    template_lines.append(f"    Generated by CloudKill v{__version__} on {report.completed_at or 'N/A'}.")
    template_lines.append("  metadata:")
    template_lines.append(f"    max-request: {len(high_conf) if high_conf else 1}")
    template_lines.append(f"    verified: {str(report.confirmed_count > 0).lower()}")
    template_lines.append(f"    cloudkill-confidence-max: {high_conf[0].confidence if high_conf else 0}")
    template_lines.append(f"  tags: cloudflare,origin-ip,recon,{report.domain.replace('.', '-')}")
    template_lines.append("")
    template_lines.append("http:")
    template_lines.append("  - method: GET")
    template_lines.append("    path:")
    template_lines.append("      - '{{BaseURL}}'")

    # Add redirect and stop-when conditions
    template_lines.append("    redirects: true")
    template_lines.append("    max-redirects: 2")
    template_lines.append("    stop-at-first-match: true")
    template_lines.append("")

    # Add matchers
    if report.enrichment_stats:
        ssl_matched = report.enrichment_stats.get("ssl_matched", 0)
    else:
        ssl_matched = sum(1 for r in high_conf if r.ssl_matches)

    # Header matcher for non-Cloudflare servers
    template_lines.append("    matchers-condition: or")
    template_lines.append("    matchers:")

    # Matcher 1: Server header not Cloudflare
    template_lines.append("      - type: word")
    template_lines.append("        part: header")
    template_lines.append("        words:")
    template_lines.append("          - 'Server'")
    template_lines.append("          - 'X-Powered-By'")
    template_lines.append("        negative: true")
    template_lines.append("        condition: or")
    template_lines.append("")

    # Matcher 2: Status code
    template_lines.append("      - type: status")
    template_lines.append("        status:")
    template_lines.append("          - 200")
    template_lines.append("")

    if ssl_matched > 0:
        # Matcher 3: SSL certificate match (for HTTPS)
        template_lines.append("      - type: word")
        template_lines.append("        part: cert")
        template_lines.append("        words:")
        template_lines.append(f"          - '{report.domain}'")
        template_lines.append("")

    # Add extractors
    template_lines.append("    extractors:")
    template_lines.append("      - type: regex")
    template_lines.append("        part: body")
    template_lines.append("        regex:")
    template_lines.append("          - '<title>(.*?)</title>'")
    template_lines.append("")
    template_lines.append("      - type: kval")
    template_lines.append("        part: header")
    template_lines.append("        kval:")
    template_lines.append("          - Server")
    template_lines.append("          - X_Powered_By")
    template_lines.append("          - Content_Type")

    # Variations (targeting each discovered IP)
    if high_conf:
        template_lines.append("")
        template_lines.append("    variations:")
        for i, result in enumerate(high_conf[:10]):  # Limit to 10 variations
            scheme = "https" if result.port in (443, 8443) else "http"
            port_suffix = f":{result.port}" if result.port not in (80, 443) else ""

            template_lines.append(f"      - variation{len(high_conf[:i+1])}:")
            template_lines.append("          url:")
            template_lines.append(f"            - '{scheme}://{result.ip}{port_suffix}'")
            template_lines.append("          headers:")
            template_lines.append(f"            Host: {report.domain}")

    # Add comments with discovered IPs
    template_lines.append("")
    template_lines.append("# Discovered by CloudFail-Killer:")
    template_lines.append(f"# Domain: {report.domain}")
    template_lines.append(f"# Total IPs: {len(high_conf)}")
    template_lines.append(f"# Confirmed: {report.confirmed_count}")
    template_lines.append("#")

    for r in high_conf[:20]:
        status = r.status.value.upper()
        provider = r.hosting_provider or r.asn_org or "unknown"
        template_lines.append(
            f"#   {r.ip}:{r.port} | {r.confidence}% | {status} | {provider} | via {r.source}"
        )

    output_path.write_text("\n".join(template_lines), encoding="utf-8")
    return output_path


def export_nuclei_targets(
    report: ScanReport,
    output_path: Path | str,
    min_confidence: int = 50,
) -> Path:
    """
    Export discovered IPs as a simple target list for Nuclei.

    Format: scheme://ip:port with Host header override.

    Args:
        report: ScanReport to export
        output_path: Output file path
        min_confidence: Minimum confidence threshold

    Returns:
        Path to the targets file
    """
    output_path = safe_output_path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    if not output_path.suffix:
        output_path = output_path.with_suffix(".txt")

    results = [
        r for r in report.results
        if r.confidence >= min_confidence and not r.is_cloudflare
    ]
    results.sort(key=lambda r: -r.confidence)

    lines: list[str] = []
    for r in results:
        scheme = "https" if r.port in (443, 8443) else "http"
        port_suffix = f":{r.port}" if r.port not in (80, 443) else ""
        lines.append(
            f"{scheme}://{r.ip}{port_suffix} # Host: {report.domain} "
            f"| confidence={r.confidence}% | source={r.source}"
        )

    output_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return output_path
